// <auto-generated />
using System;
using Issue_Tracking_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Issue_Tracking_API.Migrations
{
    [DbContext(typeof(Issue_Tracking_APIContext))]
    [Migration("20200416040837_issue")]
    partial class issue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Issue_Tracking_API.Models.IssueDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Issue_Assignee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Issue_Reported_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issue_Reporter_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssueDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
